// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onGoChange();
void onLeftRightChange();

bool go;
bool left_Right;

void initProperties(){

  ArduinoCloud.addProperty(go, READWRITE, ON_CHANGE, onGoChange);
  ArduinoCloud.addProperty(left_Right, READWRITE, ON_CHANGE, onLeftRightChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
